server:
  port: 9000

logging:
  level:
    org.springframework.security: trace

spring:
  security:
    oauth2:
      authorizationserver:
        client:
          realguardio-client:
            token:
              access-token-time-to-live: 2m 
              refresh-token-time-to-live: 60m
            registration:
              client-id: "realguardio-client"
              client-secret: "{noop}secret-rg"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
                - "password"
              redirect-uris:
                - "http://127.0.0.1:8080/login/oauth2/code/realguardio-client-oidc"
                - "http://127.0.0.1:8080/authorized"
                - "http://localhost:3000/api/auth/callback/oauth2-pkce"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/logged-out"
              scopes:
                - "openid"
                - "profile"
                - "email"
                - "message.read"
                - "message.write"
            require-authorization-consent: true
            require-proof-key: true

# Initial users configuration
users:
  initial:
    - username: user1
      password: password
      roles:
        - USER
        - ADMIN
        - REALGUARDIO_ADMIN
      enabled: true